DynestyDynamic:
  initialize:
    method: prior
  parallel:
    number_of_cores: 4
  printing:
    silence: false
  run:
    dlogz_init: 0.01
    logl_max_init: .inf
    maxcall: null
    maxcall_init: null
    maxiter: null
    maxiter_init: null
    nlive_init: 5
  search:
    bootstrap: 1
    bound: balls
    enlarge: 2
    facc: 0.6
    fmove: 0.8
    logl_max: .inf
    max_move: 101
    sample: rwalk
    slices: 6
    update_interval: 2.0
    walks: 26
Nautilus:
  search:
    n_live: 200
    n_update: null
    enlarge_per_dim: 1.2
    n_points_min: null
    split_threshold: 50
    n_networks: 2
    n_batch: 50
    n_like_new_bound: null
    vectorized: false
    seed: null
  run:
    f_live: 0.02
    n_shell: 1
    n_eff: 250
    n_like_max: .inf
    discard_exploration: false
    verbose: false
  initialize:
    method: prior
  parallel:
    number_of_cores: 2
    force_x1_cpu: false
  printing:
    silence: false
DynestyStatic:
  initialize:
    method: prior
  parallel:
    force_x1_cpu: true
    number_of_cores: 1
  printing:
    silence: true
  run:
    dlogz: null
    logl_max: .inf
    maxcall: null
    maxiter: null
  search:
    bootstrap: null
    bound: multi
    enlarge: null
    facc: 0.5
    first_update: null
    fmove: 0.9
    max_move: 100
    nlive: 150
    sample: auto
    slices: 5
    update_interval: null
    walks: 5