"""
Generate the search documentation pages from the search manifest.

    python docs/_generate_searches.py          # (re)write the generated pages
    python docs/_generate_searches.py --check  # exit 1 if any page is out of date

The pages are generated from ``python -m autofit search-manifest --json``
(``search-manifest@1``, built by ``autofit/non_linear/search/registry.py``) and
``files/citations.bib``; they are never edited by hand:

- ``docs/api/searches.rst``: the API reference, one autosummary block per family;
- ``docs/searches/index.rst``: the capability matrix ("which search");
- ``docs/searches/citations.rst``: the canonical citations page for the searches.

The pages deliberately omit ``autofit_version``, so a version bump never makes them
stale; only a change to the registry or the bibliography does.

Run from anywhere: paths resolve relative to this file. ``--check`` is run by the Docs
workflow (``.github/workflows/docs.yml``) and by ``test_autofit``.
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List

DOCS = Path(__file__).resolve().parent
REPO = DOCS.parent
BIB = REPO / "files" / "citations.bib"

HEADER = (
    ".. This file is generated by docs/_generate_searches.py from the search manifest\n"
    "   (python -m autofit search-manifest --json). Do not edit it by hand: change\n"
    "   autofit/non_linear/search/registry.py (or files/citations.bib) and re-run the\n"
    "   generator.\n\n"
)

# Bibliography fields left out of the rendered entries: long, or local to an author's
# machine. The full entries stay in files/citations.bib.
_DROPPED_BIB_FIELDS = ("abstract", "file", "keywords", "mendeley-groups")


def load_manifest() -> dict:
    """
    The search manifest, read through the public CLI exactly as other repos read it.
    """
    output = subprocess.run(
        [sys.executable, "-m", "autofit", "search-manifest", "--json"],
        capture_output=True,
        text=True,
        check=True,
        cwd=REPO,
    ).stdout
    return json.loads(output)


def _searches_by_family(manifest: dict) -> Dict[str, List[dict]]:
    grouped = {family: [] for family in manifest["families"]}
    for search in manifest["searches"]:
        grouped[search["family"]].append(search)
    return grouped


def _yes(value: bool) -> str:
    return "yes" if value else "no"


def _link(search: dict) -> str:
    return f":class:`~autofit.{search['name']}`"


def api_searches_rst(manifest: dict) -> str:
    lines = [
        HEADER,
        ".. _api_searches:\n\n",
        "===================\n",
        "Non-Linear Searches\n",
        "===================\n\n",
        "A non-linear search is an algorithm which fits a model to data.\n\n",
        f"**PyAutoFit** supports {len(manifest['searches'])} non-linear searches in "
        "three families: nested samplers (nest), Markov chain Monte Carlo (MCMC) and "
        "maximum likelihood / maximum a posteriori estimators (MLE). The "
        ":doc:`capability matrix <../searches/index>` compares them (JAX use, "
        "gradients, evidence, posterior kind, install) and the "
        ":doc:`search citations <../searches/citations>` page lists what to cite "
        "for each.\n\n",
        "**Examples / Tutorials:**\n\n",
        "- `readthedocs: example using non-linear searches "
        "<https://pyautofit.readthedocs.io/en/latest/cookbooks/search.html>`_.\n",
        "- `autofit_workspace: simple tutorial <https://github.com/PyAutoLabs/"
        "autofit_workspace/blob/main/notebooks/overview/overview_1_the_basics.ipynb>`_\n",
        "- `autofit_workspace: complex tutorial <https://github.com/PyAutoLabs/"
        "autofit_workspace/blob/main/notebooks/overview/"
        "overview_2_scientific_workflow.ipynb>`_\n",
        "- `HowToFit: tutorial lectures (detailed step-by-step examples) "
        "<https://github.com/PyAutoLabs/HowToFit>`_\n\n",
    ]
    for family, searches in _searches_by_family(manifest).items():
        title = manifest["families"][family]
        lines += [
            f"{title}\n",
            f"{'-' * len(title)}\n\n",
            ".. currentmodule:: autofit\n\n",
            ".. autosummary::\n",
            "   :toctree: _autosummary\n",
            "   :template: custom-class-template.rst\n",
            "   :recursive:\n\n",
        ]
        lines += [f"   {search['name']}\n" for search in searches]
        lines.append("\n")
    lines += [
        "There are also a number of tools which are used to customize the behaviour of "
        "non-linear searches in **PyAutoFit**,\n",
        "including directory output structure, parameter sample initialization and MCMC "
        "auto correlation analysis.\n\n",
        "Tools\n",
        "-----\n\n",
        ".. currentmodule:: autofit\n\n",
        ".. autosummary::\n",
        "   :toctree: _autosummary\n",
        "   :template: custom-class-template.rst\n",
        "   :recursive:\n\n",
        "   DirectoryPaths\n",
        "   DatabasePaths\n",
        "   Result\n",
        "   InitializerBall\n",
        "   InitializerPrior\n",
        "   ClipperNone\n",
        "   ClipperPriorBox\n",
        "   AutoCorrelationsSettings\n\n",
        "**PyAutoFit** can perform a parallelized grid-search of non-linear searches, "
        "where a subset of parameters in the\n",
        "model are fitted in over a discrete grid.\n\n",
        "**Examples / Tutorials:**\n\n",
        "- `readthedocs: example using a non-linear search grid search "
        "<https://pyautofit.readthedocs.io/en/latest/features/search_grid_search.html>`_.\n",
        "- `autofit_workspace: example using a non-linear search grid search "
        "<https://github.com/PyAutoLabs/autofit_workspace/blob/main/notebooks/features/"
        "search_grid_search.ipynb>`_\n\n",
        "GridSearch\n",
        "----------\n\n",
        ".. autosummary::\n",
        "   :toctree: _autosummary\n",
        "   :template: custom-class-template.rst\n",
        "   :recursive:\n\n",
        "   SearchGridSearch\n",
        "   GridSearchResult\n",
    ]
    return "".join(lines)


def _list_table(header: List[str], rows: List[List[str]], widths: str) -> List[str]:
    lines = [
        ".. list-table::\n",
        "   :header-rows: 1\n",
        f"   :widths: {widths}\n\n",
    ]
    for row in [header] + rows:
        lines.append(f"   * - {row[0]}\n")
        lines += [f"     - {cell}\n" for cell in row[1:]]
    lines.append("\n")
    return lines


def _example(search: dict) -> str:
    example = search["example"]
    if example is None:
        return "--"
    repo, _, rest = example.partition(":")
    path, _, section = rest.partition("#")
    url = f"https://github.com/PyAutoLabs/{repo}/blob/main/{path}"
    return f"`{Path(path).name} <{url}>`__"


def _budget(budget: dict) -> str:
    if not budget:
        return "--"
    return ", ".join(f"``{key}={value}``" for key, value in budget.items())


def searches_index_rst(manifest: dict) -> str:
    title = "Choosing a search: the capability matrix"
    lines = [
        HEADER,
        ".. _search_capability_matrix:\n\n",
        f"{'=' * len(title)}\n",
        f"{title}\n",
        f"{'=' * len(title)}\n\n",
        f"Every one of **PyAutoFit**'s {len(manifest['searches'])} non-linear searches "
        "declares its capabilities as class attributes (``autofit.Nautilus.jax_use``, "
        "``autofit.Emcee.posterior_kind``, ...). The tables below are generated from "
        "those declarations, through the versioned search manifest "
        f"(``{manifest['schema']}``)::\n\n",
        "    python -m autofit search-manifest --json\n\n",
        "The same flags are enforced at run time: a search whose ``jax_use`` is "
        "``required`` raises ``SearchException`` before fitting when the analysis is "
        "not JAX (``Analysis(use_jax=True)``).\n\n",
        "These are **static** capabilities, a property of the search class. What one "
        "run delivers can be narrower: ``SMC`` estimates the evidence only when it "
        "starts from a prior-sampling initializer, not from a warm start.\n\n",
        "Capabilities\n",
        "------------\n\n",
    ]
    header = [
        "Search",
        "Family",
        "JAX",
        "Gradients",
        "Batched",
        "Posterior",
        "Evidence",
        "Resumable",
        "Warm start",
        "Install",
        "Status",
        "Example",
    ]
    rows = []
    for search in manifest["searches"]:
        capabilities = search["capabilities"]
        rows.append(
            [
                _link(search),
                search["family"],
                capabilities["jax_use"],
                capabilities["gradient"],
                _yes(capabilities["batched"]),
                capabilities["posterior_kind"],
                _yes(capabilities["produces_evidence"]),
                _yes(capabilities["resumable"]),
                capabilities["warm_start"],
                f"``autofit[{capabilities['install_extra']}]``"
                if capabilities["install_extra"]
                else "base",
                capabilities["status"],
                _example(search),
            ]
        )
    lines += _list_table(header, rows, "14 6 8 8 7 8 7 8 8 10 9 9")
    lines += [
        "Objectives\n",
        "----------\n\n",
        "What each search's objective returns, the coordinates its backend proposes "
        "points in (``unit_cube`` backends map through the prior transform; the "
        "likelihood always receives physical parameters), the value it returns for an "
        "invalid model, and the reduced budget ``PYAUTO_TEST_MODE=1`` applies.\n\n",
    ]
    header = ["Search", "Objective", "Coordinates", "Invalid value", "Test-mode budget"]
    rows = [
        [
            _link(search),
            f"``{search['capabilities']['objective_target']['quantity']}``",
            f"``{search['capabilities']['objective_target']['space']}``",
            f"``{search['capabilities']['invalid_value']}``",
            _budget(search["capabilities"]["test_mode_budget"]),
        ]
        for search in manifest["searches"]
    ]
    lines += _list_table(header, rows, "16 18 12 12 42")
    lines += [
        "The invalid value is what the backend actually sees, not yet normalised. For "
        "the ``neg2_log_posterior`` minimizers it is conditional: a NaN or infinite "
        "likelihood is replaced by ``-inf`` and then multiplied by -2 into ``inf`` "
        "(the value listed), while a model rejected by a ``FitException`` or a failed "
        "assertion returns ``-inf``.\n\n",
    ]
    lines += [
        "Column meanings\n",
        "---------------\n\n",
        "- **JAX**: ``none`` (the backend never needs JAX), ``optional`` (a jitted or "
        "batched fast path when the analysis is JAX) or ``required`` (the backend "
        "cannot run without a traceable JAX likelihood).\n",
        "- **Gradients**: ``uses`` when the backend differentiates the likelihood.\n",
        "- **Batched**: the backend evaluates a vectorised (``jax.vmap``) likelihood "
        "over many points at once.\n",
        "- **Posterior**: ``chain`` (equally weighted MCMC draws), ``weighted`` "
        "(weighted samples) or ``point`` (a point estimate).\n",
        "- **Resumable**: an interrupted run resumes from its own checkpoint.\n",
        "- **Warm start**: ``provider`` (starts cold and can seed another search), "
        "``consumer`` (wants a warm start, e.g. from a provider's posterior) or "
        "``neutral``.\n",
        "- **Install**: ``base`` ships with ``pip install autofit``; "
        "``autofit[optional]`` needs the optional extra.\n\n",
        "See also the :doc:`search citations <citations>` page and the "
        ":doc:`API reference <../api/searches>`.\n",
    ]
    return "".join(lines)


def bib_entries(text: str) -> Dict[str, str]:
    """
    The entries of a ``.bib`` file keyed by citation key, each as its source text.
    """
    entries = {}
    for match in re.finditer(r"^@\w+\{([^,]+),", text, re.M):
        depth = 0
        for index in range(match.start(), len(text)):
            if text[index] == "{":
                depth += 1
            elif text[index] == "}":
                depth -= 1
                if depth == 0:
                    entries[match.group(1).strip()] = text[match.start() : index + 1]
                    break
    return entries


def _rendered_entry(source: str) -> str:
    kept = [
        line
        for line in source.splitlines()
        if not re.match(
            rf"\s*({'|'.join(_DROPPED_BIB_FIELDS)})\s*=", line, re.IGNORECASE
        )
    ]
    return "\n".join(kept)


def searches_citations_rst(manifest: dict, bib_text: str) -> str:
    entries = bib_entries(bib_text)
    title = "Citing the searches"
    lines = [
        HEADER,
        ".. _search_citations:\n\n",
        f"{'=' * len(title)}\n",
        f"{title}\n",
        f"{'=' * len(title)}\n\n",
        "If you used a non-linear search, please cite the software behind it as well "
        "as **PyAutoFit** (key ``pyautofit``). This is the one canonical list: it is "
        "generated from each search's declared ``citation_keys`` and the bibliography "
        "in `files/citations.bib <https://github.com/PyAutoLabs/PyAutoFit/blob/main/"
        "files/citations.bib>`__ (long fields such as abstracts are omitted here; the "
        "file has the full entries).\n\n",
    ]
    header = ["Search", "Cite", "Upstream"]
    rows = []
    for search in manifest["searches"]:
        keys = search["capabilities"]["citation_keys"]
        rows.append(
            [
                _link(search),
                ", ".join(f"``{key}``" for key in keys) if keys else "``pyautofit`` only",
                f"`{search['capabilities']['upstream_url']} "
                f"<{search['capabilities']['upstream_url']}>`__",
            ]
        )
    lines += _list_table(header, rows, "20 30 50")
    lines += ["BibTeX entries\n", "--------------\n\n"]
    keys = []
    for search in manifest["searches"]:
        for key in search["capabilities"]["citation_keys"]:
            if key not in keys:
                keys.append(key)
    missing = [key for key in keys if key not in entries]
    if missing:
        raise KeyError(f"citation keys missing from {BIB.name}: {missing}")
    for key in sorted(keys):
        lines += [
            f"``{key}``\n\n",
            ".. code-block:: bibtex\n\n",
        ]
        lines += [f"   {line}\n" if line else "\n" for line in _rendered_entry(entries[key]).splitlines()]
        lines.append("\n")
    return "".join(lines)


def generated_pages(manifest: dict) -> Dict[Path, str]:
    return {
        DOCS / "api" / "searches.rst": api_searches_rst(manifest),
        DOCS / "searches" / "index.rst": searches_index_rst(manifest),
        DOCS / "searches" / "citations.rst": searches_citations_rst(
            manifest, BIB.read_text()
        ),
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if any generated page differs from the manifest.",
    )
    arguments = parser.parse_args(argv)

    pages = generated_pages(load_manifest())

    if arguments.check:
        stale = [
            path
            for path, text in pages.items()
            if not path.exists() or path.read_text() != text
        ]
        for path in stale:
            print(f"out of date: {path.relative_to(REPO)}", file=sys.stderr)
        if stale:
            print(
                "Run `python docs/_generate_searches.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{len(pages)} generated search pages are up to date.")
        return 0

    for path, text in pages.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
